/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'customerName' : string,
  'status' : OrderStatus,
  'customerPhone' : string,
  'createdAt' : Time,
  'orderId' : bigint,
  'totalAmount' : number,
  'items' : Array<OrderedProduct>,
}
export type OrderStatus = { 'pending' : null } |
  { 'outForDelivery' : null } |
  { 'delivered' : null } |
  { 'accepted' : null };
export interface OrderedProduct {
  'productId' : bigint,
  'productName' : string,
  'quantity' : bigint,
  'price' : number,
}
export interface Product {
  'stockQuantity' : bigint,
  'name' : string,
  'unit' : string,
  'productId' : bigint,
  'imageEmoji' : string,
  'category' : ProductCategory,
  'price' : number,
}
export type ProductCategory = { 'groceries' : null } |
  { 'snacks' : null } |
  { 'fruits' : null } |
  { 'beverages' : null } |
  { 'vegetables' : null } |
  { 'personalCare' : null } |
  { 'dairy' : null } |
  { 'household' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [string, number, string, ProductCategory, bigint, string],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrderById' : ActorMethod<[bigint], [] | [Order]>,
  'getOrdersByPhone' : ActorMethod<[string], Array<Order>>,
  'getOrdersInLast24Hours' : ActorMethod<[], Array<Order>>,
  'getOrdersPaginated' : ActorMethod<[bigint, bigint], Array<Order>>,
  'getOutOfStockProducts' : ActorMethod<[], Array<Product>>,
  'getProductById' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[ProductCategory], Array<Product>>,
  'getProductsPaginated' : ActorMethod<[bigint, bigint], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[string, string, Array<OrderedProduct>], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'seedProducts' : ActorMethod<[], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [bigint, string, number, string, ProductCategory, bigint, string],
    undefined
  >,
  'updateStock' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];