/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductCategory = IDL.Variant({
  'groceries' : IDL.Null,
  'snacks' : IDL.Null,
  'fruits' : IDL.Null,
  'beverages' : IDL.Null,
  'vegetables' : IDL.Null,
  'personalCare' : IDL.Null,
  'dairy' : IDL.Null,
  'household' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'outForDelivery' : IDL.Null,
  'delivered' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Time = IDL.Int;
export const OrderedProduct = IDL.Record({
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
});
export const Order = IDL.Record({
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'customerPhone' : IDL.Text,
  'createdAt' : Time,
  'orderId' : IDL.Nat,
  'totalAmount' : IDL.Float64,
  'items' : IDL.Vec(OrderedProduct),
});
export const Product = IDL.Record({
  'stockQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'productId' : IDL.Nat,
  'imageEmoji' : IDL.Text,
  'category' : ProductCategory,
  'price' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, ProductCategory, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getOrdersByPhone' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getOrdersInLast24Hours' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrdersPaginated' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'getOutOfStockProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func(
      [ProductCategory],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProductsPaginated' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(OrderedProduct)],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'seedProducts' : IDL.Func([], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updateProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        ProductCategory,
        IDL.Nat,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateStock' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductCategory = IDL.Variant({
    'groceries' : IDL.Null,
    'snacks' : IDL.Null,
    'fruits' : IDL.Null,
    'beverages' : IDL.Null,
    'vegetables' : IDL.Null,
    'personalCare' : IDL.Null,
    'dairy' : IDL.Null,
    'household' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'outForDelivery' : IDL.Null,
    'delivered' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Time = IDL.Int;
  const OrderedProduct = IDL.Record({
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
  });
  const Order = IDL.Record({
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'customerPhone' : IDL.Text,
    'createdAt' : Time,
    'orderId' : IDL.Nat,
    'totalAmount' : IDL.Float64,
    'items' : IDL.Vec(OrderedProduct),
  });
  const Product = IDL.Record({
    'stockQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'productId' : IDL.Nat,
    'imageEmoji' : IDL.Text,
    'category' : ProductCategory,
    'price' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, ProductCategory, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getOrdersByPhone' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getOrdersInLast24Hours' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrdersPaginated' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getOutOfStockProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [ProductCategory],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsPaginated' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(OrderedProduct)],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'seedProducts' : IDL.Func([], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updateProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          ProductCategory,
          IDL.Nat,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateStock' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };